{% set name = "HFRadarPy" %}
{% set version = "1.0.0.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/rowg/HFRadarPy/archive/{{ version }}.tar.gz
  sha256: b053c0d0a5bd870bf9a390d7acea7e85ddb20b60bbe2fb9fe611caeb2dc4f277

build:
  entry_points:
    - hfradarpy=hfradarpy.cli:main
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=3.10
    - pip
  run:
    - python >=3.10
    - xarray
    - netcdf4
    - pyproj
    - click
    - dask-core
    - geopandas
    - cartopy
    - matplotlib-base
    - cmocean
    - joblib
    - basemap
    - geopy
    - oceans
    - pytest

test:
  imports:
    - hfradarpy
  commands:
    - pip check
    - hfradarpy --help
  requires:
    - pip

about:
  home: https://github.com/rowg/hfradarpy
  summary: 'Toolbox to work with High Frequency Radar (HFR) files for coastal ocean observing.'
  license: MIT
  license_file: LICENSE
  
extra:
  recipe-maintainers:
    - najascutellatus
    - teresaupdyke
